### ISSUE TITLE
Get this error

### ISSUE THREAD

**Issue by Botmakingisafunsport** [LukeProducts/YouTubeViewer-2.0#3]
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self.run()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self.run()
    self._target(*self._args, **self._kwargs)
  File "YouTube_Bot.py", line 62, in traffic
  File "YouTube_Bot.py", line 62, in traffic
    self._target(*self._args, **self._kwargs)
  File "YouTube_Bot.py", line 62, in traffic
    driver = webdriver.Chrome("libs/drivers/chromedriver.exe", options=opts)
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    driver = webdriver.Chrome("libs/drivers/chromedriver.exe", options=opts)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self._target(*self._args, **self._kwargs)
  File "YouTube_Bot.py", line 62, in traffic
    driver = webdriver.Chrome("libs/drivers/chromedriver.exe", options=opts)
    self.service.start()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 86, in start
    driver = webdriver.Chrome("libs/drivers/chromedriver.exe", options=opts)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
    self.service.start()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 86, in start
    self.service.start()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 86, in start
    raise WebDriverException(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
    raise WebDriverException(
    raise WebDriverException(

selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by LukeProducts** [comment]
Try to start the program with admin privileges.

With kind regards 
LukeProducts
